name: 'Deploy Infra'

on:
  push:
    branches:
      - main

env:
  DESTROY: false
  TF_VERSION: 1.10.5
  IMAGE_NAME: ci-cd-app
  TAG_APP: v1.0.0
  ECS_SERVICE: app-service
  ECS_CLUSTER: app-prod-cluster
  ENVIRONMENT: prod

jobs:
     
  Deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: app

    steps:
      - name: Download do Repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform | Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform | Set up statefile S3 Bucket for Backend
        run: |
            echo "terraform {
              backend \"s3\" {
                bucket   = \"${{ secrets.AWS_ACCOUNT_ID }}-tfstate\"
                key      = \"app-${{ env.ENVIRONMENT }}.tfstate\"
              }
            }" >> provider.tf
            cat provider.tf

      - name: Terraform | Initialize backend
        run: terraform init
        working-directory: ./infra

      - name: Terraform | Check Syntax IaC Code
        run: terraform validate
        working-directory: ./infra

      - name: Terraform | Plan
        run: terraform plan -out tfplan.binary
        working-directory: ./infra

      - name: Terraform Destroy
        if: env.DESTROY == 'true'
        run: terraform destroy -auto-approve -input=false
        working-directory: ./infra

      - name: Terraform Creating and Update
        if: env.DESTROY != 'true'
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra
